"""add facilities_room

Revision ID: 0ba3375377c5
Revises: 12a085261c51
Create Date: 2025-04-01 10:44:46.495282

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "0ba3375377c5"
down_revision: Union[str, None] = "12a085261c51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
